### ISSUE TITLE
Exception while running this script

### ISSUE THREAD

**Issue by vipsy** [levyitay/AddSecurityExceptionAndroid#1]
The apk was a production apk.
Command:  ./addSecurityExceptions.sh original_apkfile.apk 
I tried `sudo` as well but same exception. 

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_2621850001535583170.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 136, --version-name, 1.5.32, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL1968343114380978702.tmp, -0, arsc, -0, sql, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/com.example.hh_1.5.32-136/res, -M, /tmp/com.example.hh_1.5.32-136/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_2621850001535583170.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 136, --version-name, 1.5.32, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL1968343114380978702.tmp, -0, arsc, -0, sql, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/com.example.hh_1.5.32-136/res, -M, /tmp/com.example.hh_1.5.32-136/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_2621850001535583170.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 136, --version-name, 1.5.32, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL1968343114380978702.tmp, -0, arsc, -0, sql, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/com.example.hh_1.5.32-136/res, -M, /tmp/com.example.hh_1.5.32-136/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
jarsigner: unable to open jar file: ./com.example.hh_1.5.32-136_new.apk

**Comment by levyitay** [comment]
can you send the apk?

**Comment by abhishekjebaraj** [comment]
The solution here https://github.com/iBotPeaches/Apktool/issues/1376#issuecomment-400357321 worked. I had to edit the shell file and added the '-r' parameter.
