### ISSUE TITLE
Cannot build APK

### ISSUE THREAD

**Issue by AlexMaguey** [levyitay/AddSecurityExceptionAndroid#10]
I am using the defualt keystore option.

I: Using Apktool 2.2.4 on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /var/root/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: font/lato_semi_bold_italic.ttf
S: Could not decode file, replacing by FALSE value: font/lato_regular_italic.ttf
S: Could not decode file, replacing by FALSE value: font/lato_regular.ttf
S: Could not decode file, replacing by FALSE value: font/lato_bold.ttf
S: Could not decode file, replacing by FALSE value: font/lato_light.ttf
S: Could not decode file, replacing by FALSE value: font/lato_light_italic.ttf
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Removing 1.apk framework file...
Building new APK base_new.apk
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /tmp/base/res font
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_4241409149410193573.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 27, --version-code, 14336, --version-name, 4.14.0, --no-version-vectors, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL5722066547825444843.tmp, -0, arsc, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_4241409149410193573.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 27, --version-code, 14336, --version-name, 4.14.0, --no-version-vectors, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL5722066547825444843.tmp, -0, arsc, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/brut_util_Jar_4241409149410193573.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 27, --version-code, 14336, --version-name, 4.14.0, --no-version-vectors, -F, /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/APKTOOL5722066547825444843.tmp, -0, arsc, -0, arsc, -I, /var/root/Library/apktool/framework/1.apk, -S, /tmp/base/res, -M, /tmp/base/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)

**Comment by levyitay** [comment]
Can you share the apk?

**Comment by roblav96** [comment]
getting the same error

**Comment by levyitay** [comment]
Hi
I update the apktool.jar to a newer version... let me know if that helps.

**Comment by abhishekjebaraj** [comment]
The solution here worked for me. https://github.com/iBotPeaches/Apktool/issues/1376#issuecomment-400357321 Edit the shell script file and add the '-r' parameter.
