### ISSUE TITLE
No resource identifier found for attribute 'networkSecurityConfig' in package 'android'

### ISSUE THREAD

**Issue by aommm** [levyitay/AddSecurityExceptionAndroid#2]
Problem
----
When running the script, I got this:
```

W: /tmp/My_Lil_App_v3.0.0/AndroidManifest.xml:3: error: No resource identifier found for attribute 'networkSecurityConfig' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/brut_util_Jar_6566168031649658064.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 3, --version-name, 3.0.0, -F, /var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/APKTOOL8666138019041163139.tmp, -0, arsc, -I, /Users/aom/Library/apktool/framework/1.apk, -S, /tmp/My_Lil_App_v3.0.0/res, -M, /tmp/My_Lil_App_v3.0.0/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/brut_util_Jar_6566168031649658064.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 3, --version-name, 3.0.0, -F, /var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/APKTOOL8666138019041163139.tmp, -0, arsc, -I, /Users/aom/Library/apktool/framework/1.apk, -S, /tmp/My_Lil_App_v3.0.0/res, -M, /tmp/My_Lil_App_v3.0.0/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/brut_util_Jar_6566168031649658064.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 3, --version-name, 3.0.0, -F, /var/folders/fl/vg_18w991bq_jr2bflnhr2b00000gn/T/APKTOOL8666138019041163139.tmp, -0, arsc, -I, /Users/aom/Library/apktool/framework/1.apk, -S, /tmp/My_Lil_App_v3.0.0/res, -M, /tmp/My_Lil_App_v3.0.0/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
jarsigner: unable to open jar file: ./My_Lil_App_v3.0.0_new.apk
```

Solution
----
Turned out I had apktool 2.2.0 installed.
When I upgraded it to 2.2.2, the mentioned warning did not appear.

Opening an issue here to let you and others know. Might want to add a "apktool 2.2.2 or above is required" to readme. Thanks for a nice utility!

**Comment by levyitay** [comment]
Happy to hear you managed to solve it :)
