### ISSUE TITLE
jarsigner: unable to open jar file

### ISSUE THREAD

**Issue by kychanbp** [levyitay/AddSecurityExceptionAndroid#26]
I tried to add exception to this app: http://client.3g.fang.com/http/wap/index.html

But I got `jarsigner: unable to open jar file`

```
I: Using Apktool 2.4.1 on soufun_android_30000_9.0.1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: /tmp/soufun_android_30000_9.0.1/AndroidManifest.xml (Permission denied)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:164)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: /tmp/soufun_android_30000_9.0.1/AndroidManifest.xml (Permission denied)
	at brut.directory.FileDirectory.getFileOutputLocal(FileDirectory.java:80)
	at brut.directory.AbstractDirectory.getFileOutput(AbstractDirectory.java:116)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:160)
	... 5 more
Caused by: java.io.FileNotFoundException: /tmp/soufun_android_30000_9.0.1/AndroidManifest.xml (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at brut.directory.FileDirectory.getFileOutputLocal(FileDirectory.java:78)
	... 7 more
cp: cannot create regular file '/tmp/soufun_android_30000_9.0.1/res/xml/./network_security_config.xml': Permission denied
I: Removing 1.apk framework file...
Building new APK soufun_android_30000_9.0.1_new.apk
I: Using Apktool 2.4.1
brut.directory.PathNotExist: apktool.yml
jarsigner: unable to open jar file: ./soufun_android_30000_9.0.1_new.apk

```

**Comment by levyitay** [comment]
Ok so I downloaded the apk, not sure what it does but looks suspicious btw. 
There is a dex file in the apk which is cannot be decode, but don't see how this relates to that error msg you pasted here.
The error msg you pasted here is more of permission issue you might have on your env. 
I updated the script to ignore the decoding the dex files (no used really)
Try again, if you still get permission denied exception make sure you have read/write permission to  your /tmp folder.
