### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2

### ISSUE THREAD

**Issue by andykais** [levyitay/AddSecurityExceptionAndroid#34]
this [fb messenger apk](https://m.apkpure.com/facebook-messenger/com.facebook.orca) throws an exception when ran through the tool. I also worry that the script doesnt exit when a failure occurs. It just ends with "Resigned APK successfully"

```
andrew  AddSecurityExceptionAndroid  ./addSecurityExceptions.sh Messenger\ –\ Text\ and\ Video\ Chat\ for\ Free_v321.0.0.16.119_apkpure.com.apk 
I: Using Apktool 2.4.1 on Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:119)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
mkdir: cannot create directory ‘/tmp/Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com/res/xml’: No such file or directory
cp: cannot create regular file '/tmp/Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com/res/xml/.': No such file or directory
grep: /tmp/Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com/AndroidManifest.xml: No such file or directory
sed: can't read /tmp/Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com/AndroidManifest.xml: No such file or directory
W: Can't empty framework directory, no file found at: /home/andrew/.local/share/apktool/framework/1.apk
Building temp APK Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com_temp.apk
I: Using Apktool 2.4.1
brut.directory.PathNotExist: apktool.yml
jarsigner: unable to open jar file: ./Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com_temp.apk
Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-p] [-v] [-z] <align> infile.zip outfile.zip
       zipalign -c [-p] [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -p: memory page alignment for stored shared object files
  -v: verbose output
  -z: recompress using Zopfli
Resigned APK successfully Messenger – Text and Video Chat for Free_v321.0.0.16.119_apkpure.com_new.apk
```

it also looks like zipalign args need to be wrapped in quotes, otherwise filenames with spaces will give the zipalign error

**Comment by levyitay** [comment]
@andykais I updated the script with newer apktool and processes, let me know if that work for you

**Comment by levyitay** [comment]
update and fixed
