### ISSUE TITLE
Some differents issues 

### ISSUE THREAD

**Issue by Unrectified** [levyitay/AddSecurityExceptionAndroid#42]
With google play and google authenticator:

```W: C:\Users\natha\AppData\Local\Temp\google-play\AndroidManifest.xml:450: error: unexpected element <property> found in <manifest><application>.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\natha\AppData\Local\Temp\brut_util_Jar_53403817284728628775203475470522108827.tmp, link, -o, C:\Users\natha\AppData\Local\Temp\APKTOOL5818146599572765108.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 632, --version-name, 6.32, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\natha\AppData\Local\Temp\APKTOOL13381975660644436397.tmp, -0, arsc, -I, C:\Users\natha\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\natha\AppData\Local\Temp\google-play\AndroidManifest.xml, C:\Users\natha\AppData\Local\Temp\google-play\build\resources.zip]
Running Zip Align on google-play_temp.apk and creating google-play_new.apk
Unable to open 'google-play_temp.apk' as zip archive: No such file or directory
Signing temp file google-play_new.apk with androiddebugkey
Exception in thread "main" java.io.FileNotFoundException: .\google-play_new.apk (Le fichier sp▒cifi▒ est introuvable)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:213)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:425)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:94)
Resigned APK successfully google-play_new.apk
```

With whattsap:

```
I: Copying C:\Users\natha\AppData\Local\Temp\wh-beta classes6.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-v22\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml:16: error: not well-formed (invalid token).
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-v22\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml: error: file failed to compile.
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-w360dp-land\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml:15: error: not well-formed (invalid token).
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-w360dp-land\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml: error: file failed to compile.
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-w480dp-land\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml:18: error: not well-formed (invalid token).
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout-w480dp-land\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml: error: file failed to compile.
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml:16: error: not well-formed (invalid token).
W: C:\Users\natha\AppData\Local\Temp\wh-beta\res\layout\APKTOOL_DUPLICATE_layout_0x7f0e0490.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\natha\AppData\Local\Temp\brut_util_Jar_139662251541546996016159031797196954281.tmp, compile, --dir, C:\Users\natha\AppData\Local\Temp\wh-beta\res, --legacy, -o, C:\Users\natha\AppData\Local\Temp\wh-beta\build\resources.zip]
Running Zip Align on wh-beta_temp.apk and creating wh-beta_new.apk
Unable to open 'wh-beta_temp.apk' as zip archive: No such file or directory
Signing temp file wh-beta_new.apk with androiddebugkey
Exception in thread "main" java.io.FileNotFoundException: .\wh-beta_new.apk (Le fichier sp▒cifi▒ est introuvable)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:213)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:425)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:94)
Resigned APK successfully wh-beta_new.apk
```

with insta:

```
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-anydpi\mipmaps.xml:10: error: invalid value for type 'mipmap'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-anydpi\mipmaps.xml:11: error: invalid value for type 'mipmap'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-anydpi\mipmaps.xml: error: file failed to compile.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-ar\raws.xml:3: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-ar\raws.xml:4: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-ar\raws.xml:5: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-ar\raws.xml:6: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-ar\raws.xml: error: file failed to compile.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-cs\raws.xml:3: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-cs\raws.xml:4: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-cs\raws.xml:5: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-cs\raws.xml:6: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\natha\AppData\Local\Temp\insta\res\values-cs\raws.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\natha\AppData\Local\Temp\brut_util_Jar_50262736559726349904460440347337111354.tmp, compile, --dir, C:\Users\natha\AppData\Local\Temp\insta\res, --legacy, -o, C:\Users\natha\AppData\Local\Temp\insta\build\resources.zip]
Running Zip Align on insta_temp.apk and creating insta_new.apk
Unable to open 'insta_temp.apk' as zip archive: No such file or directory
Signing temp file insta_new.apk with androiddebugkey
Exception in thread "main" java.io.FileNotFoundException: .\insta_new.apk (Le fichier sp▒cifi▒ est introuvable)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:213)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:425)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:94)
Resigned APK successfully insta_new.apk
```

with facebook lite:

```
W: C:\Users\natha\AppData\Local\Temp\face-l\AndroidManifest.xml:86: error: attribute android:allowCrossUidActivitySwitchFromBelow not found.
W: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\natha\AppData\Local\Temp\brut_util_Jar_30226181019046903726639873235790358270.tmp, link, -o, C:\Users\natha\AppData\Local\Temp\APKTOOL395074234045454283.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 506401075, --version-name, 430.0.0.4.109, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\natha\AppData\Local\Temp\APKTOOL3944774591302152871.tmp, -0, arsc, -I, C:\Users\natha\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\natha\AppData\Local\Temp\face-l\AndroidManifest.xml, C:\Users\natha\AppData\Local\Temp\face-l\build\resources.zip]
Running Zip Align on face-l_temp.apk and creating face-l_new.apk
Unable to open 'face-l_temp.apk' as zip archive: No such file or directory
Signing temp file face-l_new.apk with androiddebugkey
Exception in thread "main" java.io.FileNotFoundException: .\face-l_new.apk (Le fichier sp▒cifi▒ est introuvable)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:213)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:425)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:94)
Resigned APK successfully face-l_new.apk
```

Hope it will help a bit

**Comment by theGeekyLad** [comment]
Facing exactly the same issue as above for WhatsApp. What could be the reason?

**Comment by levyitay** [comment]
Looks like you are running the process on Windows machine, its currently only able to run properly on Linux / MacOS
